# Generated by Django 2.2.17 on 2021-06-27 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical_history', '0002_itemvalue_usermedicalhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvalue',
            name='type',
            field=models.CharField(default=None, max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemvalue',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medical_history.Item'),
        ),
    ]
