version: "3"

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: siellano_historical_medicals_backend_prod_django
    container_name: siellano_historical_medicals_backend_prod
    volumes:
      - .:/app
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    ports:
      - "9011:80"
    external_links:
      - postgres-dev:postgres
    networks:
      - containers_network
    environment:
      - "VIRTUAL_HOST=api.farsys.pcaingenieria.co"
    command: /start
