version: "3"

volumes:
  local_mongo_data: {}

services:
  mongo:
    build:
      context: .
      dockerfile: ./compose/production/mongo/Dockerfile
    image: siellano_mongo_dev
    container_name: siellano_mongo_dev
    volumes:
      - local_mongo_data:/data/db
    env_file:
      - ./.envs/.local/.mongo
    ports:
      - "27017:27017"
    command: mongod
    networks:
      - containers

  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: siellano_historical_medicals_backend_local
    container_name: siellano_historical_medicals_backend_local
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.mongo
    ports:
      - "9011:8000"
    depends_on:
      - mongo
    networks:
      - containers

    # environment:
    #   - "VIRTUAL_HOST=api.siellano-dev.com"
    command: /start

networks:
  containers:
    external: true
