# Generated by Django 2.2.17 on 2021-07-20 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_ips_productioncenter_program_state_typerequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='Created At')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='Modified At')),
                ('request_datetime', models.DateTimeField()),
                ('suggested_datetime', models.DateTimeField()),
                ('patient_appointment_uuid', models.CharField(max_length=120)),
                ('ips', models.CharField(max_length=120)),
                ('production_code', models.CharField(max_length=120)),
                ('sale_document', models.CharField(blank=True, max_length=120, null=True)),
                ('first_time', models.BooleanField()),
                ('programs', models.TextField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules_patient_appointment', to='schedules.Appointment')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules_patient_appointment_state', to='services.State')),
                ('type_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules_patient_appointment_type_request', to='services.TypeRequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules_patient_appointment_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
