from .nacionality import Nacionality
from .country import Country
from .department import Department
from .city import City
from .usual_occupation import UsualOccupation
from .special_population import SpecialPopulation
from .sexual_orientation import SexualOrientation
from .social_security_scheme import SocialSecurityScheme
from .eps import Eps
from .civil_status import CivilStatus
from .scholarship import Scholarship
from .ethnic_group import EthnicGroup
from .type_degree_disability import TypeDegreeDisability
from .relationship_person_in_charge import RelationshipPersonInCharge
from .hc_open_place import HcOpenPlace
from .hc_transfer_to import HcTransferTo
from .diagnose import Diagnose
from .category import Category
from .ips import Ips
from .production_center import ProductionCenter
from .program import Program
from .state import State
from .type_request import TypeRequest
from .external_cause import ExternalCause
from .diagnostic_aid import DiagnosticAid
from .specialist import Specialist
from .medicine import Medicine
from .presentation import Presentation
from .exam import Exam
